export const API = {
  LOGIN: "/api/Auth/login",
  PROFILE: "/api/Auth/profile",
  USERS: "/api/Auth/users",
  PRODUCTS: "/products",
  PRODUCT_UPLOAD: "/products/upload-image",
  PRODUCT_LOW_STOCK: "/products/low-stock",
  PRODUCT_STOCK_ALERTS: "/products/stock-alerts",
  ORDERS: "/orders",
  MY_ORDERS: "/orders/me",
  ORDER_STATUS: "/orders",
  COUPONS: "/coupons",
  RETURNS: "/returns",
  AUDIT_LOGS: "/audit-logs",
  ANALYTICS_SUMMARY: "/analytics/summary",
  EXPORT_ORDERS: "/exports/orders.csv",
  EXPORT_USERS: "/exports/users.csv",
  EXPORT_PRODUCTS: "/exports/products.csv",
  EXPORT_RETURNS: "/exports/returns.csv",
};
