export const API = {
  LOGIN: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/api/Auth/login",
  PROFILE: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/api/Auth/profile",
  USERS: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/api/Auth/users",
  PRODUCTS: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/products",
  PRODUCT_UPLOAD: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/products/upload-image",
  PRODUCT_LOW_STOCK: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/products/low-stock",
  PRODUCT_STOCK_ALERTS: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/products/stock-alerts",
  ORDERS: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/orders",
  MY_ORDERS: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/orders/me",
  ORDER_STATUS: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/orders",
  COUPONS: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/coupons",
  RETURNS: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/returns",
  AUDIT_LOGS: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/audit-logs",
  ANALYTICS_SUMMARY: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/analytics/summary",
  EXPORT_ORDERS: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/exports/orders.csv",
  EXPORT_USERS: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/exports/users.csv",
  EXPORT_PRODUCTS: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/exports/products.csv",
  EXPORT_RETURNS: "https://vercel.com/piyush-patils-projects-765e81f9/yogita-fashion-api/GvVxVHLNdoWjYoVEpsEoE1sWoafq/exports/returns.csv",
};
